SELECT COUNT(*) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM FISH_INFO
GROUP BY MONTH(TIME)
ORDER BY MONTH

# Oracle
# SELECT COUNT(*) AS FISH_COUNT, TO_CHAR(TIME, 'MM') AS MONTH
# FROM FISH_INFO
# GROUP BY TO_CHAR(TIME, 'MM')
# ORDER BY MONTH
