SELECT COUNT(*) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM FISH_INFO
GROUP BY MONTH(TIME)
ORDER BY MONTH

# Oracle
# SELECT COUNT(TIME) AS FISH_COUNT, TIME AS MONTH
# FROM FISH_INFO
# GROUP BY TO_NUMBER(SUBSTR(TO_CHAR(TIME), 6,8))
# ORDER BY MONTH